### PR TITLE
Fix sdl2.c not compiling

### PR DESCRIPTION
**Pull request by PoroCYon**
See https://github.com/idris-lang/Idris-dev/blob/master/rts/idris_rts.h#L281 .

### CODE REVIEW

**Comment by steshaw** [comment]
Thanks, looks good!

What disturbs me is that I don't get a compiler warning (or error) on Mac. Would you mind saying how you provoked the compiler error?

**Comment by PoroCYon** [comment]
I simply compiled it, perhaps it's because I have a newer GCC (6.3.1), or your Idris install is out-of-date (I'm using the upstream code).

**Comment by steshaw** [comment]
Thanks @PoroCYon. I was using the released version idris-0.99. It was a recent change that provokes the compile error.

**Comment by PoroCYon** [comment]
Ah, thanks for figuring it out.

**Pull request merged**
